gunicorn:
  build: django/
  hostname: gunicorn
  expose:
    - "8000"
  environment:
    DO_COLLECTSTATIC: True
    WAIT_FOR_PG: True

nginx:
  build: deploy/docker/containers/nginx/
  ports:
    - "80:80"
