gunicorn:
  build: django/
  hostname: gunicorn
  expose:
    - "8000"
  environment:
    DO_COLLECTSTATIC: True
    WAIT_FOR_PG: True

nginx:
  image: dekked/nginx-docker
  ports:
    - "80:80"
  volumes:
    - deploy/docker/containers/nginx/templates/:/templates
